### ISSUE TITLE
Landscape Layout not working correctly in iPad with iOS 5.1

### ISSUE THREAD

**Issue by josea** [ondalabs/OLGhostAlertView#14]
Hi, 

I took the master branch demo, and added the shouldAutorotate... method below to the OLViewController.m to allow it rotate. 

It rotates, but it doesn't work correctly: the alert popups are still displayed like the iPad was in portrait mode. It is like the view is missing a transformation. 
- (BOOL)shouldAutorotateToInterfaceOrientation:(UIInterfaceOrientation)interfaceOrientation
  {
  return YES;
  }

Note: maybe related: I have to add this to may .pch to resolve compiling issues: 
# define NS_ENUM(_type, _name) enum _name : _type _name; enum _name : _type

**Comment by josea** [comment]
Note: if you add this to the show method it will work "correctly" when in landscape. However, the rotation doesn't work fine. 

```
self.transform = window.rootViewController.view.transform;
self.frame = CGRectMake(self.frame.origin.y, self.frame.origin.x, self.frame.size.width, self.frame.size.height);
```

**Comment by radutzan** [comment]
Sorry about that. Broke this with commit 0aa66def84d16350ed8e9a66847a7bfc59534821. Looking into it.

**Comment by josea** [comment]
I noticed that you are adding the  "ghost view" to the Window. I do not know if you did that in the previous versions, but the Window doesn't have the rotation transformation (not sure if that helps).

**Comment by radutzan** [comment]
That's exactly the issue. I'll try to fix this today or tomorrow. Adding as a subview of the window was issue #1, and I rushed to fix it because of #11. Not sure if I'll revert to adding it as a subview of the Root View Controller (or Presented VC if there is one) or just manually transform it.

**Comment by radutzan** [comment]
I promise I won't promise any more ETAs. This fix is coming someday.

**Comment by josea** [comment]
Thank you :)
