### ISSUE TITLE
OLGhostAlertView is not recognized in the Podfile

### ISSUE THREAD

**Issue by mal3k** [ondalabs/OLGhostAlertView#6]
I always setup third party libraries within cocoapods, so in the Podfile, I added the name of this library:

platform :ios
pod ' OLGhostAlertView'

However, when installing the pod, this library seems not to be recognized by the pod file:

Resolving dependencies of `./Podfile'
Updating spec repositories
Resolving dependencies for target`default' (iOS 4.3)
[!] Unable to find a pod named `OLGhostAlertView'

Is there any reason why? Thanx in advance.

**Comment by dtorres** [comment]
You have a space in pod ' OLGhostAlertView', maybe is that?

On 19-01-2013, at 19:50, lucaazori notifications@github.com wrote:

I always setup third party libraries within cocoapods, so in the Podfile, I
added the name of this library:

platform :ios
pod ' OLGhostAlertView'

However, when installing the pod, this library seems not to be recognized
by the pod file:

Resolving dependencies of ./Podfile'
Updating spec repositories
Resolving dependencies for targetdefault' (iOS 4.3)
[!] Unable to find a pod named `OLGhostAlertView'

Is there any reason why? Thanx in advance.

—
Reply to this email directly or view it on
GitHubhttps://github.com/ondalabs/OLGhostAlertView/issues/6.

**Comment by mal3k** [comment]
Oh, it was a typo when pasting it here, I removed that space and the issue still.

**Comment by dtorres** [comment]
I just remembered this pod is not in the Cocoapods/Specs repo.
You're gonna have to add the git url to your podfile in the mean time

**Comment by kilink** [comment]
Are you planning on adding the pod.specfile to Cocoapods?

**Comment by dtorres** [comment]
Already in progress :)

**Comment by kilink** [comment]
Thanks!
