### ISSUE TITLE
Logic Errors in XCode 4.6  for iOS6.1

### ISSUE THREAD

**Issue by DoctorG** [ondalabs/OLGhostAlertView#9]
Can you help me get rid of these warnings?

1.
In: (id)initWithTitle:(NSString *)title message:(NSString *)message timeout:(NSTimeInterval)timeout dismissible:(BOOL)dismissible:
CGFloat xPosition = floorf((screenRect.size.width / 2) - (totalWidth / 2));

OLGhostAlertView.m:146:33: The left operand of '/' is a garbage value

2.
In:  didChangeScreenBounds:
self.frame = CGRectMake(floorf((screenRect.size.width / 2) - (self.frame.size.width / 2)), self.frame.origin.y, self.frame.size.width, self.frame.size.height);

OLGhostAlertView.m:146:33: The left operand of '/' is a garbage value
1. 
   In:  (void)setPosition:(OLGhostAlertViewPosition)position:
   yPosition = screenRect.size.height - self.frame.size.height - self.bottomMargin;

OLGhostAlertView.m:319:25: The left operand of '-' is a garbage value
OLGhostAlertView.m:323:32: The left operand of '/' is a garbage value

**Comment by radutzan** [comment]
We're not getting those warnings. We're using OLGAV in two of our projects, with the latest debugger. Do you see them in the sample project? Can anybody else confirm they are getting these?

**Comment by madhavan-rp** [comment]
Tested it in XCode 4.6 and the warnings do show up. They come when you build and analyze. I have fixed it and made a pull request.

**Comment by radutzan** [comment]
Cool, thanks a lot!

**Comment by DoctorG** [comment]
Thank you!
Very nice control. Very much appreciate you sharing it!
